spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/columbus
    username: avalon
    password: avalon
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        dialect: com.sigma.columbus.core.data.PostgreSQLDialectCustom